[package]
name = "benchhash"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bench]]
name = "bench"
path = "bench/bench.rs"
harness = false

[dependencies]
criterion = "0.3.5"
murmur3 = "0.5.1"
sha-1 = "0.10.0"
